### ISSUE TITLE
价格变动范围参数和手续费是什么关系

### ISSUE THREAD

**Issue by qhxin** [Kucoin-academy/avg-position#13]
```
补充：一般价格变动范围设置在手续费的4倍左右为基准开始调优较为合理，市场活跃时，可以是手续费的1.5~2倍左右。市场不太活跃时，手续费的8倍，十倍，甚至二十，五十倍都是可以的。

```

按描述中所说的，一般价格变动范围设置在手续费的4倍左右为基准开始调优较为合理，这里的手续费是怎么计算的？是用仓位总额乘以手续费率？

**Comment by 1bazinga25** [comment]
> ```
> 补充：一般价格变动范围设置在手续费的4倍左右为基准开始调优较为合理，市场活跃时，可以是手续费的1.5~2倍左右。市场不太活跃时，手续费的8倍，十倍，甚至二十，五十倍都是可以的。
> ```
> 
> 按描述中所说的，一般价格变动范围设置在手续费的4倍左右为基准开始调优较为合理，这里的手续费是怎么计算的？是用仓位总额乘以手续费率？

**Comment by 1bazinga25** [comment]
是的，也就是说你的总成本

**Comment by qhxin** [comment]
获取账户在各个交易对手续费率的的接口是什么呢？API文档没有看到有。

**Comment by 1bazinga25** [comment]
您是指现货还是期货

**Comment by 1bazinga25** [comment]
我们暂时没有提供这样的接口。
