### ISSUE TITLE
 cannot import name 'Market' from 'kucoin.client'

### ISSUE THREAD

**Issue by caosbad** [Kucoin-academy/avg-position#5]
I use pip3 install python-kucoin pacakge, but got import error

```
Traceback (most recent call last):
  File "./avg_position.py", line 7, in <module>
    from kucoin.client import Market, User, Trade
ImportError: cannot import name 'Market' from 'kucoin.client' (/usr/local/lib/python3.7/site-packages/kucoin/client.py)
```

did I get The wrong lib or something wrong ?

**Comment by 1bazinga25** [comment]
Have you installed python-kucoin successful?

**Comment by 1bazinga25** [comment]
Sorry for my mistake.

**Comment by caosbad** [comment]
Problem resolved, Thank you !

**Comment by s-teamup** [comment]
I facing same issue.
ImportError: cannot import name 'Market' from 'kucoin.client' (/opt/homebrew/lib/python3.9/site-packages/kucoin/client.py)

Issue not resolved even though run below commands.

pip3 uninstall python-kucoin
pip3 install kucoin-python

Python version is 3.9.7

Please help.

ERROR:
-------------
Traceback (most recent call last):
  File "/avg-position/avg_position.py", line 7, in <module>
    from kucoin.client import Market, User, Trade, Client
ImportError: cannot import name 'Market' from 'kucoin.client' (/opt/homebrew/lib/python3.9/site-packages/kucoin/client.py)
---------------

**Comment by s-teamup** [comment]
I am using mac air M1. I have reinstalled Python latest version. Its working
